language: C

sudo: true

install:
  - curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
  - tar zxf lua-5.3.5.tar.gz
  - cd lua-5.3.5
  - make linux test

script:
  - ls
  - cd ~/lua/test
  - pwd
  - bash all.sh
