name: tests
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install lua
        run: |
          cd ${{ github.workspace }}; \
          curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz; \
          tar zxf lua-5.4.4.tar.gz; \
          cd lua-5.4.4; \
          make linux test; \
          cd ..
      - name: Run tests  
        run: |
          cd ${{ github.workspace }}; pwd; ls ..; \
          lua-5.4.4/src/lua l5.lua -t all 
      - run: echo "ğŸ This job's status is ${{ job.status }}."
